# uv configuration for dataknobs monorepo
# https://docs.astral.sh/uv/reference/settings/

# Index configuration
index-url = "https://pypi.org/simple"

# Extra index for test packages  
extra-index-url = ["https://test.pypi.org/simple"]

# Cache directory
cache-dir = ".uv-cache"

# Compile bytecode for faster startup
compile-bytecode = true

# Prerelease handling
prerelease = "if-necessary-or-explicit"
