# BASE: image that other versions are built upon; only include things common to all versions
FROM python:3

# Install necessary system packages and clean-up
RUN chmod 1777 /tmp \
  && apt-get update && apt-get install -y --allow-unauthenticated --no-install-recommends  \
      curl build-essential python3-dev \
      gfortran cmake libopenblas-dev \
      graphviz nmap emacs-nox \
      nodejs npm \
  && apt-get clean \
  && rm -rf /var/tmp /tmp /var/lib/apt/lists/* \
  && mkdir -p /var/tmp /tmp

# Install jupyter (python3)
RUN pip install jupyterlab ipywidgets jupyterlab_widgets

# Install uv and tox
RUN curl -LsSf https://astral.sh/uv/install.sh | sh
ENV PATH="/root/.cargo/bin:${PATH}"
RUN pip3 install tox

# used as a volume (connects to the host machine's disk at runtime)
RUN mkdir -p /data

WORKDIR /workdir
