"""LLM abstraction layer for FSM patterns.

This module provides a unified abstraction layer for working with various LLM providers
including OpenAI, Anthropic, Ollama, and others.
"""

from .base import (
    LLMProvider,
    AsyncLLMProvider,
    SyncLLMProvider,
    LLMConfig,
    LLMMessage,
    LLMResponse,
    LLMStreamResponse,
    CompletionMode,
    ModelCapability,
    ModelConstraints,
    ToolCall,
    normalize_llm_config,
)
from .model_profile import (
    BundledResourceSource,
    CallableModelMetadataSource,
    ConfigOverrideSource,
    LayeredModelProfileResolver,
    LiveApiSource,
    ModelMetadataSource,
    ModelPricing,
    ModelProfile,
    PartialModelProfile,
    merge_partials,
    model_metadata_sources,
)
from .providers import (
    OpenAIProvider,
    AnthropicProvider,
    BedrockProvider,
    BedrockConverseAdapter,
    OllamaProvider,
    HuggingFaceProvider,
    EchoProvider,
    CachingEmbedProvider,
    EmbeddingCache,
    MemoryEmbeddingCache,
    LLMProviderFactory,
    create_llm_provider,
    create_embedding_provider,
    create_caching_provider,
)
from .utils import (
    TemplateStrategy,
    MessageTemplate,
    MessageBuilder,
    ResponseParser,
    TokenCounter,
    CostCalculator,
    render_conditional_template,
    chain_prompts,
    create_few_shot_prompt,
)

__all__ = [
    # Base classes
    'LLMProvider',
    'AsyncLLMProvider',
    'SyncLLMProvider',
    'LLMConfig',
    'LLMMessage',
    'LLMResponse',
    'LLMStreamResponse',
    'CompletionMode',
    'ModelCapability',
    'ModelConstraints',
    'ToolCall',
    'normalize_llm_config',
    # Model-metadata substrate
    'ModelProfile',
    'ModelPricing',
    'PartialModelProfile',
    'ModelMetadataSource',
    'LayeredModelProfileResolver',
    'CallableModelMetadataSource',
    'ConfigOverrideSource',
    'BundledResourceSource',
    'LiveApiSource',
    'merge_partials',
    'model_metadata_sources',
    # Providers
    'OpenAIProvider',
    'AnthropicProvider',
    'BedrockProvider',
    'BedrockConverseAdapter',
    'OllamaProvider',
    'HuggingFaceProvider',
    'EchoProvider',
    'CachingEmbedProvider',
    'EmbeddingCache',
    'MemoryEmbeddingCache',
    'LLMProviderFactory',
    'create_llm_provider',
    'create_embedding_provider',
    'create_caching_provider',
    # Utils
    'TemplateStrategy',
    'MessageTemplate',
    'MessageBuilder',
    'ResponseParser',
    'TokenCounter',
    'CostCalculator',
    'render_conditional_template',
    'chain_prompts',
    'create_few_shot_prompt',
]
